title: Cinch
logo: "/assets/images/logo-highres-name-web.png"
description: Database migrations made simple.
theme: just-the-docs
color_scheme: dark
markdown: kramdown
highlighter: none # disable, using highlight.js
url: https://www.cinch.live
exclude:
    - logo

# footer
back_to_top: true
back_to_top_text: "Back to top"

# header
heading_anchors: true
aux_links:
    '<img width=32 src="/assets/images/github.png">':
        - "https://github.com/cinch-project"

callouts_level: loud # or loud
callouts:
    highlight:
        color: yellow
    important:
        title: important
        color: purple
    new:
        color: green
    note:
        title: note
        color: blue
    warning:
        title: warning
        color: red
#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
