title: Cinch
description: Database migrations made simple.
theme: just-the-docs
color_scheme: light
markdown: kramdown
highlighter: none # disable, using highlight.js
url: https://www.cinch.live

# footer
back_to_top: true
back_to_top_text: "Back to top"

# header
heading_anchors: true
aux_links:
    '<img src="/assets/images/github.png">':
        - "https://github.com/cinchsoft"

callouts_level: quiet # or loud
callouts:
    highlight:
        color: yellow
    important:
        color: purple
    new:
        color: green
    note:
        color: blue
    warning:
        color: red
#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
